data:
  augmentations:
    cutmix: 0.1
    degrees: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    mixup: 0.1
    mosaic: 1.0
    perspective: 0.0
    random_erasing: 0.1
    scale: 0.6
    shear: 0.0
    translate: 0.15
  fast_inference_subset: 0.02
  split_strategy: random
  test_data_proportion: 1.0
  test_path: data_organized/test
  test_split: 0.2
  train_data_proportion: 0.1
  train_path: data_organized/train
  train_split: 0.7
  val_data_proportion: 0.1
  val_path: data_organized/val
  val_split: 0.1
evaluation:
  batch_size: 8
  bbox_output_dir: evaluation_results/bbox_images
  compute_map: true
  compute_precision_recall: true
  confidence_threshold: 0.25
  data_dir: data_organized/test
  iou_threshold: 0.5
  max_eval_images: 10
  model_path: checkpoints/yolov8n_final.pt
  nms_threshold: 0.45
  output_dir: evaluation_results
  save_bbox_images: true
  save_plots: true
  save_results: true
  test_images_dir: data_organized/test/images
  test_labels_dir: data_organized/test/labels
hardware:
  device: auto
  gradient_accumulation_steps: 1
  macos_compatibility: true
  mixed_precision: true
  num_gpus: 1
  num_workers: 0
  pin_memory: false
inference:
  batch_size: 1
  benchmark_runs: 100
  confidence_threshold: 0.25
  fast_mode: true
  max_detections: 100
  model_path: checkpoints/yolov8n_final.pt
  nms_threshold: 0.45
  output_dir: outputs
  save_predictions: true
  subset_size: 0.02
  test_image: data_organized/test/images/525.png
  warmup_runs: 10
logging:
  checkpoint_dir: checkpoints
  console_level: INFO
  export_onnx: true
  file_level: DEBUG
  log_dir: logs
  log_every_n_steps: 10
  onnx_export_path: checkpoints/yolov8n_final.onnx
  save_every_n_epochs: 5
model:
  confidence_threshold: 0.25
  depth_multiplier: 0.33
  input_size: 640
  name: yolov8n
  nms_threshold: 0.45
  num_classes: 3
  num_scales: 3
  width_multiplier: 0.25
training:
  batch_size: 1
  cutmix: 0.1
  dropout: 0.1
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2.0
  label_smoothing: 0.1
  learning_rate: 0.0003
  loss_weights:
    bbox: 0.1
    cls: 0.6
    obj: 0.7
  lr_decay_factor: 0.1
  lr_scheduler: cosine
  min_delta: 0.005
  mixup: 0.1
  num_epochs: 2
  patience: 8
  warmup_epochs: 8
  warmup_method: linear
  warmup_start_lr: 0.0001
  weight_decay: 0.0003
